/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Administrator
 */

public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    
    Operaciones lola=new Operaciones();
    
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @Override
    public boolean isLocationByPlatform() {
        return super.isLocationByPlatform(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        SubTitulo = new javax.swing.JLabel();
        N = new javax.swing.JTextField();
        crear = new javax.swing.JButton();
        consultar = new javax.swing.JButton();
        buscarValor = new javax.swing.JButton();
        buscarPosicion = new javax.swing.JButton();
        modificarPosicion = new javax.swing.JButton();
        modificarValor = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        mensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setText("Operaciones con arreglos");

        SubTitulo.setText("Tamaño del arreglo");

        N.addActionListener(this::NActionPerformed);

        crear.setText("Crear arreglo");
        crear.addActionListener(this::crearActionPerformed);

        consultar.setText("Consultar");
        consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultarMouseClicked(evt);
            }
        });

        buscarValor.setText("Buscar por valor");
        buscarValor.addActionListener(this::buscarValorActionPerformed);

        buscarPosicion.setText("Buscar por posicion");
        buscarPosicion.addActionListener(this::buscarPosicionActionPerformed);

        modificarPosicion.setText("modificar por posicion");
        modificarPosicion.addActionListener(this::modificarPosicionActionPerformed);

        modificarValor.setText("modificar por valor");
        modificarValor.addActionListener(this::modificarValorActionPerformed);

        eliminar.setText("Eliminar");
        eliminar.addActionListener(this::eliminarActionPerformed);

        mensaje.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SubTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(N, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(crear)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(consultar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(eliminar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buscarPosicion)
                                    .addComponent(buscarValor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modificarValor)
                                    .addComponent(modificarPosicion)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(Titulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Titulo)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubTitulo)
                    .addComponent(N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear)
                    .addComponent(consultar)
                    .addComponent(buscarPosicion)
                    .addComponent(modificarPosicion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarValor)
                    .addComponent(modificarValor)
                    .addComponent(eliminar))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
            
        if (N.getText().equals("Primero llena la casilla")){
            N.setText("Valor requerido");
        }else{
            lola.crear(Integer.parseInt(N.getText()));
        }
        
    }//GEN-LAST:event_crearActionPerformed

    private void consultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarMouseClicked
        consultar.addActionListener(e -> lola.consultar());
    }//GEN-LAST:event_consultarMouseClicked

    private void modificarPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarPosicionActionPerformed
        modificarPosicion.addActionListener(e -> lola.modificarPorPosicion());
    }//GEN-LAST:event_modificarPosicionActionPerformed

    private void NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NActionPerformed

    private void buscarPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPosicionActionPerformed
        buscarPosicion.addActionListener(e -> lola.buscarPorPosicion());
    }//GEN-LAST:event_buscarPosicionActionPerformed

    private void buscarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarValorActionPerformed
        buscarValor.addActionListener(e -> lola.buscarPorValor());
    }//GEN-LAST:event_buscarValorActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        eliminar.addActionListener(e -> lola.eliminar());
    }//GEN-LAST:event_eliminarActionPerformed

    private void modificarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarValorActionPerformed
        modificarValor.addActionListener(e -> lola.modificarPorValor());
    }//GEN-LAST:event_modificarValorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField N;
    private javax.swing.JLabel SubTitulo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton buscarPosicion;
    private javax.swing.JButton buscarValor;
    private javax.swing.JButton consultar;
    private javax.swing.JButton crear;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel mensaje;
    private javax.swing.JButton modificarPosicion;
    private javax.swing.JButton modificarValor;
    // End of variables declaration//GEN-END:variables
}
